// This file is auto-generated by @hey-api/openapi-ts

export const ObjectIdSchema = {
    type: 'string'
} as const;

export const UserSchema = {
    type: 'object',
    properties: {
        id: {
            '$ref': '#/components/schemas/ObjectId'
        },
        openid: {
            type: 'string'
        },
        sessionKey: {
            type: 'string'
        },
        name: {
            type: 'string'
        },
        hashedPassword: {
            type: 'string'
        },
        school: {
            type: 'string'
        },
        role: {
            type: 'string'
        },
        jwt: {
            type: 'string'
        },
        expend: {
            type: 'number',
            format: 'double'
        },
        orderNum: {
            type: 'integer',
            format: 'int32'
        },
        address: {
            type: 'string'
        },
        createdAt: {
            type: 'string',
            format: 'date-time'
        }
    }
} as const;

export const ProductCateSchema = {
    type: 'object',
    properties: {
        id: {
            '$ref': '#/components/schemas/ObjectId'
        },
        title: {
            type: 'string'
        },
        status: {
            type: 'integer',
            description: 'status=0为下架，前端不显示',
            format: 'int32'
        },
        priority: {
            type: 'integer',
            description: '优先级，便于设置显示顺序，已自动排序',
            format: 'int32'
        },
        delete: {
            type: 'integer',
            description: '对于delete=1的，后端不返回',
            format: 'int32'
        }
    }
} as const;

export const OptionValueSchema = {
    required: ['uuid'],
    type: 'object',
    properties: {
        uuid: {
            type: 'string'
        },
        value: {
            type: 'string',
            description: '加购商品的可选项的可选值，如对于"规格"，value可以为"中杯"'
        },
        priceAdjustment: {
            type: 'integer',
            description: '该可选项的价格调整，>=0',
            format: 'int32'
        }
    },
    description: '加购商品的可选项, key=ProductOption.id'
} as const;

export const ProductSchema = {
    type: 'object',
    properties: {
        id: {
            '$ref': '#/components/schemas/ObjectId'
        },
        cateId: {
            '$ref': '#/components/schemas/ObjectId'
        },
        name: {
            type: 'string'
        },
        imgURL: {
            type: 'string'
        },
        price: {
            type: 'integer',
            description: '基础价格',
            format: 'int32'
        },
        describe: {
            type: 'string',
            description: '详情页描述'
        },
        short_desc: {
            type: 'string',
            description: '菜单列表中，name下面展示的简介'
        },
        status: {
            type: 'integer',
            description: 'status=0为下架，前端过滤不显示',
            format: 'int32'
        },
        delete: {
            type: 'integer',
            description: '对于delete=1的，后端不返回',
            format: 'int32'
        },
        productOptions: {
            type: 'object',
            additionalProperties: {
                type: 'array',
                description: '加购商品的可选项, key=ProductOption.id',
                items: {
                    '$ref': '#/components/schemas/OptionValue'
                }
            },
            description: '加购商品的可选项, key=ProductOption.id'
        }
    }
} as const;

export const ProductOptionSchema = {
    type: 'object',
    properties: {
        id: {
            '$ref': '#/components/schemas/ObjectId'
        },
        name: {
            type: 'string',
            description: '商品的可选项名称，如"规格"'
        },
        values: {
            type: 'array',
            description: '对于一个可选项，所有的可能选值，商铺管理用',
            items: {
                '$ref': '#/components/schemas/OptionValue'
            }
        }
    }
} as const;

export const FixDeliveryInfoSchema = {
    type: 'object',
    properties: {
        id: {
            '$ref': '#/components/schemas/ObjectId'
        },
        school: {
            type: 'string',
            description: '对应User学生认证后的学校'
        },
        times: {
            type: 'array',
            description: '可选时间',
            items: {
                type: 'string',
                description: '可选时间'
            }
        },
        addresses: {
            type: 'array',
            description: '可选地址',
            items: {
                type: 'string',
                description: '可选地址'
            }
        }
    }
} as const;

export const ActivitySchema = {
    type: 'object',
    properties: {
        id: {
            '$ref': '#/components/schemas/ObjectId'
        },
        title: {
            type: 'string',
            description: '活动名'
        },
        imgURL: {
            type: 'string',
            description: '活动图片'
        },
        describe: {
            type: 'string',
            description: '活动介绍'
        }
    }
} as const;

export const ProcessorMapSchema = {
    type: 'object',
    properties: {
        id: {
            '$ref': '#/components/schemas/ObjectId'
        },
        state: {
            type: 'string'
        },
        event: {
            type: 'string'
        },
        customerTypes: {
            type: 'array',
            items: {
                type: 'string'
            }
        },
        scenes: {
            type: 'array',
            items: {
                type: 'string'
            }
        },
        processorIds: {
            type: 'array',
            items: {
                type: 'integer',
                format: 'int32'
            }
        }
    }
} as const;

export const DeliveryInfoSchema = {
    type: 'object',
    properties: {
        school: {
            type: 'string'
        },
        address: {
            type: 'string',
            description: '绑定到具体订单实例的已选地址'
        },
        time: {
            type: 'string',
            description: '绑定到具体订单实例的已选时间',
            format: 'date-time'
        }
    },
    description: '定时达配送信息'
} as const;

export const OrderSchema = {
    type: 'object',
    properties: {
        id: {
            '$ref': '#/components/schemas/ObjectId'
        },
        userId: {
            '$ref': '#/components/schemas/ObjectId'
        },
        state: {
            type: 'string',
            description: '自动填充状态'
        },
        customerType: {
            type: 'string',
            description: '顾客类型，可选："北大学生业务"，"清华学生业务"，"未认证为学生身份的用户业务"'
        },
        scene: {
            type: 'string',
            description: '场景，可选："堂食"，"外带"，"定时达"'
        },
        deliveryInfo: {
            '$ref': '#/components/schemas/DeliveryInfo'
        },
        items: {
            type: 'array',
            description: '订单所含商品列表',
            example: '[example1,example2...]',
            items: {
                '$ref': '#/components/schemas/OrderItem'
            }
        },
        orderNum: {
            type: 'integer',
            description: '自动填充订单号',
            format: 'int32'
        },
        remark: {
            type: 'string',
            description: '顾客备注'
        },
        merchantNote: {
            type: 'string',
            description: '商家备注'
        },
        totalPrice: {
            type: 'integer',
            description: '前端先计算一个，根据sum(OrderItem.price)-优惠券，后端会check',
            format: 'int32'
        },
        createdAt: {
            type: 'string',
            description: '自动填充创建时间',
            format: 'date-time'
        }
    },
    description: '就是订单呀'
} as const;

export const OrderItemSchema = {
    type: 'object',
    properties: {
        productId: {
            '$ref': '#/components/schemas/ObjectId'
        },
        optionValues: {
            type: 'object',
            additionalProperties: {
                '$ref': '#/components/schemas/OptionValue'
            },
            description: '商品选项，key为ProductOption.id, value为一个完整的OptionValue'
        },
        name: {
            type: 'string',
            description: 'Product.name'
        },
        price: {
            type: 'integer',
            description: '根据Product.price和目前optionValues中OptionValue.priceAdjustment计算的价格',
            format: 'int32'
        }
    },
    description: '订单其中的一个商品'
} as const;

export const JSONObjectSchema = {
    type: 'object',
    properties: {
        empty: {
            type: 'boolean'
        }
    },
    additionalProperties: {
        type: 'object'
    }
} as const;

export const ServiceResultObjectObjectSchema = {
    type: 'object',
    properties: {
        data: {
            type: 'object'
        },
        context: {
            type: 'object'
        },
        msg: {
            type: 'string'
        },
        success: {
            type: 'boolean'
        }
    }
} as const;

export const LoginDTOSchema = {
    required: ['password', 'username'],
    type: 'object',
    properties: {
        username: {
            type: 'string'
        },
        password: {
            type: 'string'
        }
    }
} as const;

export const ResponseBodyDTOUserDTOSchema = {
    type: 'object',
    properties: {
        msg: {
            type: 'string'
        },
        data: {
            '$ref': '#/components/schemas/UserDTO'
        }
    }
} as const;

export const UserDTOSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        openid: {
            type: 'string'
        },
        name: {
            type: 'string'
        },
        school: {
            type: 'string'
        },
        role: {
            type: 'string'
        }
    }
} as const;